name: main

permissions:
  contents: write


on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true


      - name: Setup depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH


      - name: Checkout devtools-frontend
        run: |
          git clone --depth=1 https://chromium.googlesource.com/devtools/devtools-frontend
          gclient config https://chromium.googlesource.com/devtools/devtools-frontend --unmanaged


      - name: Build devtools-frontend
        run: |
          echo "FRONTEND_GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          sed -i 's/is_official_build = false/is_official_build = true/g' build_overrides/BUILDCONFIG.gn
          gclient sync
          vpython3 third_party/node/node.py --output scripts/run_build.mjs
        working-directory: devtools-frontend


      - name: Minify devtools-frontend
        run: |
          find devtools-frontend/out/Default/gen/front_end -type f \( \
            -name "*.d" -o \
            -name "*.grd" -o \
            -name "*.gz" -o \
            -name "*.test.js" -o \
            -name "*.js.map" -o \
            -name "*.ts.map" -o \
            -name "*.d.ts" -o \
            -name "*-tsconfig.json" \
            -name "Tests.js" \
            -name "tests.txt" \
          \) -exec rm -f {} +

          mv devtools-frontend/out/Default/gen/front_end app/src/main/assets/devtools-frontend


      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-overwrite-existing: true


      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks


      - name: Build App Release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          bash gradlew assembleRelease


      - name: Build App Debug
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          bash gradlew assembleDebug


      - name: Find APKs
        run: |
          echo "APK_FILE_RELEASE=$(find app/build/outputs/apk/release -name '*.apk')" >> $GITHUB_ENV
          echo "APK_FILE_DEBUG=$(find app/build/outputs/apk/debug -name '*.apk')" >> $GITHUB_ENV


      - name: Show Artifacts Summary
        run: |
          echo "### Build Success :rocket:" >> $GITHUB_STEP_SUMMARY

          echo "Devtools-frontend Git Hash: ${{ env.FRONTEND_GIT_HASH }}" >> $GITHUB_STEP_SUMMARY

          echo "|APK|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:--------:|:----------|" >> $GITHUB_STEP_SUMMARY

          release=($(sha256sum ${{ env.APK_FILE_RELEASE }}))
          echo "|Release|$release|" >> $GITHUB_STEP_SUMMARY

          debug=($(sha256sum ${{ env.APK_FILE_DEBUG }}))
          echo "|Debug|$debug|" >> $GITHUB_STEP_SUMMARY


      - name: Upload Artifacts Release
        uses: actions/upload-artifact@v4
        with:
          name: FoldDevtools-release-${{ github.sha }}
          path: ${{ env.APK_FILE_RELEASE }}


      - name: Upload Artifacts Debug
        uses: actions/upload-artifact@v4
        with:
          name: FoldDevtools-debug-${{ github.sha }}
          path: ${{ env.APK_FILE_DEBUG }}


      - name: Upload Artifacts Frontend
        uses: actions/upload-artifact@v4
        with:
          name: devtools-frontend-${{ env.FRONTEND_GIT_HASH }}
          path: app/src/main/assets/devtools-frontend


      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: FoldDevtools Build ${{ github.run_number }}
          body: |
            ## FoldDevtools Release

            Commit:
            ${{ github.sha }}

            Devtools frontend:
            ${{ env.FRONTEND_GIT_HASH }}

          files: |
            ${{ env.APK_FILE_RELEASE }}
            ${{ env.APK_FILE_DEBUG }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
